name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run pylint
        run: pylint --exit-zero .

      - name: Run black
        run: black --check .

      - name: Publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: dist/
