name: Ojd Daps Terraform Validate

on:
  workflow_dispatch:
  pull_request:
    branches:
      - dev
    paths:
      - ojd_daps/deploy/**
      - .github/workflows/terraform-validate.yml

jobs:
  ojd-daps-validate:
    name: Validate Ojd-daps Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Terraform configure
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.15.3

      - name: Validate AWS Batch Job definition deploy
        id: validate_deploy_ojd_daps_job_definition
        env:
          DAPS_TERRAFORM_WORKINGDIR: ojd_daps/deploy/terraform/
        run: |
          echo "Validate terraform config."
          cd ${DAPS_TERRAFORM_WORKINGDIR}
          terraform init -input=false
          terraform validate
